inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  SuggestExtensions: false
  # 最新のルールを適用する
  NewCops: enable
  # 何のルールに引っかかったか表示する
  DisplayCopNames: true
  # rubocop対象外(リポジトリ毎で調節)
  Exclude:
    - "Gemfile"
    - "bin/**/*"
    - "db/**/*"
    - "log/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "lib/**/*"
    - "config/environments/*"
    - "config/puma.rb"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "spec/**/*"

### ルールのカスタマイズ

# メソッドの改行ルール
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# 日本語にコメントを許可
Style/AsciiComments:
  Enabled: false

# クラスにコメントを残さなくても良い
Style/Documentation:
  Enabled: false

# コントローラ等のモジュールをネストしての宣言
Style/ClassAndModuleChildren:
  Enabled: false

# 文字列のfreeze（Ruby3からは自動でfreezeされるので要らない）
Style/FrozenStringLiteralComment:
  Enabled: false

# ガード節の提案（難しいので一旦false）
Style/GuardClause:
  Enabled: false

# 文字列のダブルクォートチェック
Style/StringLiterals:
  Enabled: false

# シンボルによる配列の%記法のチェック
Style/SymbolArray:
  Enabled: false
  # EnforcedStyle: brackets

# 文字列による配列の%記法のチェック
Style/WordArray:
  Enabled: false

# 変数名に数字を許可
Naming/VariableNumber:
  Enabled: false

# = と == の指摘
Lint/AssignmentInCondition:
  Enabled: false

# メソッド名等の命名の指摘
Naming/PredicateName:
  Enabled: false

# 未i18nのチェック
Rails/I18nLocaleTexts:
  Enabled: false

# 環境変数をfetchで設定する指摘
Style/FetchEnvVar:
  Enabled: false

Metrics/AbcSize:
  Max: 70

Metrics/BlockLength:
  Max: 40

Metrics/MethodLength:
  Max: 30

Metrics/LineLength:
  Max: 150

Metrics/PerceivedComplexity:
  Max: 10

Style/StringConcatenation:
  Enabled: false

Lint/ShadowedArgument:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Rails/SkipsModelValidations:
  Exclude:
    - 'app/controllers/reservations_controller.rb'

Rails/HelperInstanceVariable:
  Exclude:
    - 'app/helpers/user_sessions_helper.rb' # HelperInstanceVariableを特定のファイルで無視する

Lint/UnusedBlockArgument:
  Exclude:
    - 'app/jobs/confirm_maching_date_job.rb' # UnusedBlockArgumentを特定のファイルで無視する

