:concurrency: 1
:max_retries: 2
:queues:
  - default
  - confirm_date
  - guest
:scheduler:
  :schedule:
    change_question_state_job:
      cron: '0 0 * * * *'    # １時間ごと
      class: ChangeQuestionStateJob
    access_route_page_job:
      cron: '0 */10 * * * *'
      class: AccessRoutePageJob
    delete_guest_user_job:
      cron: '0 0 * * * *'  
      class: DeleteGuestUserJob 

